ci/cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,8 +1,4 @@
-name: CI/CD Pipeline
-
-on:
-  push:
-    branches: [main]
+# ...
 
 jobs:
   # 빌드
@@ -15,7 +11,14 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '20.x'
+          node-version: '14.x' # 사용하려는 Node.js 버전에 맞게 수정
+
+      # 이 부분에서 EC2_USER 확인
+      - name: Check EC2_USER
+        run: |
+          EC2_USER="$(whoami)"
+          echo "EC2_USER is $EC2_USER"
+        id: check-ec2-user
 
       - name: Install Dependencies
         run: npm install
@@ -33,6 +36,17 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
+
+      # 이 부분에서 EC2_USER를 확인하고 일치 여부를 검사
+      - name: Check EC2_USER
+        run: |
+          EC2_USER="$(whoami)"
+          echo "EC2_USER is $EC2_USER"
+          if [ "$EC2_USER" != "${{ secrets.EC2_USER }}" ]; then
+            echo "Error: EC2_USER does not match!"
+            exit 1
+          fi
+        id: check-ec2-user
 
       - name: Copy files to the server
         uses: appleboy/scp-action@master
@@ -55,3 +69,5 @@ jobs:
             cd /home/ubuntu/myblog
             npm install --production
             pm2 restart all
+
+# ...
