ci/cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -42,6 +42,17 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+        # 이 부분에서 EC2_USER를 확인하고 일치 여부를 검사
+      - name: Check EC2_USER
+        run: |
+          EC2_USER="$(whoami)"
+          echo "EC2_USER is $EC2_USER"
+          if [ "$EC2_USER" != "${{ secrets.EC2_USER }}" ]; then
+            echo "Error: EC2_USER does not match!"
+            exit 1
+          fi
+        id: check-ec2-user
+
       - name: Copy files to the server
         uses: appleboy/scp-action@master
         with:
